name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: raven-actions/actionlint@v2.0.0
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: aschbacd/gitlint-action@v1.2.0
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: articulate/actions-markdownlint@v1.1.0
