name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: aschbacd/gitlint-action@v1.2.0
